
# default rules
homepage:
  url:   /
  param: { module: job, action: index }


default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*

  job_show_user:
    url:   /job/:company/:location/:id/:position
    param: { module: job, action: show }
