<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2020/03/18 09:10:38
return array(

  // sfDoctrinePlugin_module_libs

  // sfDoctrinePlugin_lib
  'sfdoctrinecli' => 'E:/projets epitech/tuto-symfo-1-4/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/cli/sfDoctrineCli.class.php',
  'sfdoctrineconnectionlistener' => 'E:/projets epitech/tuto-symfo-1-4/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php',
  'sfdoctrineconnectionprofiler' => 'E:/projets epitech/tuto-symfo-1-4/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionProfiler.class.php',
  'sfdoctrinedatabase' => 'E:/projets epitech/tuto-symfo-1-4/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php',
  'sfwebdebugpaneldoctrine' => 'E:/projets epitech/tuto-symfo-1-4/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/debug/sfWebDebugPanelDoctrine.class.php',
  'sfformdoctrine' => 'E:/projets epitech/tuto-symfo-1-4/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormDoctrine.class.php',
  'sfformfilterdoctrine' => 'E:/projets epitech/tuto-symfo-1-4/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php',
  'sfdoctrinecolumn' => 'E:/projets epitech/tuto-symfo-1-4/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineColumn.class.php',
  'sfdoctrineformfiltergenerator' => 'E:/projets epitech/tuto-symfo-1-4/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormFilterGenerator.class.php',
  'sfdoctrineformgenerator' => 'E:/projets epitech/tuto-symfo-1-4/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormGenerator.class.php',
  'sfdoctrinegenerator' => 'E:/projets epitech/tuto-symfo-1-4/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineGenerator.class.php',
  'swift_doctrinespool' => 'E:/projets epitech/tuto-symfo-1-4/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/mailer/Swift_DoctrineSpool.class.php',
  'sfdoctrinepager' => 'E:/projets epitech/tuto-symfo-1-4/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php',
  'sfdoctrinerecord' => 'E:/projets epitech/tuto-symfo-1-4/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php',
  'sfdoctrinerecordi18nfilter' => 'E:/projets epitech/tuto-symfo-1-4/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php',
  'sfdoctrineroute' => 'E:/projets epitech/tuto-symfo-1-4/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php',
  'sfdoctrineroutecollection' => 'E:/projets epitech/tuto-symfo-1-4/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRouteCollection.class.php',
  'sfdoctrineexception' => 'E:/projets epitech/tuto-symfo-1-4/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/sfDoctrineException.class.php',
  'sfdoctrinebasetask' => 'E:/projets epitech/tuto-symfo-1-4/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php',
  'sfdoctrinebuilddbtask' => 'E:/projets epitech/tuto-symfo-1-4/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildDbTask.class.php',
  'sfdoctrinebuildfilterstask' => 'E:/projets epitech/tuto-symfo-1-4/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFiltersTask.class.php',
  'sfdoctrinebuildformstask' => 'E:/projets epitech/tuto-symfo-1-4/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFormsTask.class.php',
  'sfdoctrinebuildmodeltask' => 'E:/projets epitech/tuto-symfo-1-4/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildModelTask.class.php',
  'sfdoctrinebuildschematask' => 'E:/projets epitech/tuto-symfo-1-4/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSchemaTask.class.php',
  'sfdoctrinebuildsqltask' => 'E:/projets epitech/tuto-symfo-1-4/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSqlTask.class.php',
  'sfdoctrinebuildtask' => 'E:/projets epitech/tuto-symfo-1-4/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildTask.class.php',
  'sfdoctrinecleanmodelfilestask' => 'E:/projets epitech/tuto-symfo-1-4/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCleanModelFilesTask.class.php',
  'sfdoctrineconfiguredatabasetask' => 'E:/projets epitech/tuto-symfo-1-4/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineConfigureDatabaseTask.class.php',
  'sfdoctrinecreatemodeltables' => 'E:/projets epitech/tuto-symfo-1-4/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCreateModelTablesTask.class.php',
  'sfdoctrinedatadumptask' => 'E:/projets epitech/tuto-symfo-1-4/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataDumpTask.class.php',
  'sfdoctrinedataloadtask' => 'E:/projets epitech/tuto-symfo-1-4/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataLoadTask.class.php',
  'sfdoctrinedeletemodelfilestask' => 'E:/projets epitech/tuto-symfo-1-4/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDeleteModelFilesTask.class.php',
  'sfdoctrinedqltask' => 'E:/projets epitech/tuto-symfo-1-4/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDqlTask.class.php',
  'sfdoctrinedropdbtask' => 'E:/projets epitech/tuto-symfo-1-4/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDropDbTask.class.php',
  'sfdoctrinegenerateadmintask' => 'E:/projets epitech/tuto-symfo-1-4/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateAdminTask.class.php',
  'sfdoctrinegeneratemigrationsdbtask' => 'E:/projets epitech/tuto-symfo-1-4/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDbTask.class.php',
  'sfdoctrinegeneratemigrationsdifftask' => 'E:/projets epitech/tuto-symfo-1-4/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDiffTask.class.php',
  'sfdoctrinegeneratemigrationsmodelstask' => 'E:/projets epitech/tuto-symfo-1-4/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsModelsTask.class.php',
  'sfdoctrinegeneratemigrationtask' => 'E:/projets epitech/tuto-symfo-1-4/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationTask.class.php',
  'sfdoctrinegeneratemoduleforroutetask' => 'E:/projets epitech/tuto-symfo-1-4/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleForRouteTask.class.php',
  'sfdoctrinegeneratemoduletask' => 'E:/projets epitech/tuto-symfo-1-4/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleTask.class.php',
  'sfdoctrineinsertsqltask' => 'E:/projets epitech/tuto-symfo-1-4/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineInsertSqlTask.class.php',
  'sfdoctrinemigratetask' => 'E:/projets epitech/tuto-symfo-1-4/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineMigrateTask.class.php',
  'sftesterdoctrine' => 'E:/projets epitech/tuto-symfo-1-4/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/test/sfTesterDoctrine.class.php',
  'sfvalidatordoctrinechoice' => 'E:/projets epitech/tuto-symfo-1-4/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php',
  'sfvalidatordoctrineunique' => 'E:/projets epitech/tuto-symfo-1-4/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineUnique.class.php',
  'sfwidgetformdoctrinechoice' => 'E:/projets epitech/tuto-symfo-1-4/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoice.class.php',

  // project
  'baseform' => 'E:/projets epitech/tuto-symfo-1-4/lib/form/BaseForm.class.php',

  // project_model
  'basejobeetaffiliate' => 'E:/projets epitech/tuto-symfo-1-4/lib/model/doctrine/base/BaseJobeetAffiliate.class.php',
  'basejobeetcategory' => 'E:/projets epitech/tuto-symfo-1-4/lib/model/doctrine/base/BaseJobeetCategory.class.php',
  'basejobeetcategoryaffiliate' => 'E:/projets epitech/tuto-symfo-1-4/lib/model/doctrine/base/BaseJobeetCategoryAffiliate.class.php',
  'basejobeetjob' => 'E:/projets epitech/tuto-symfo-1-4/lib/model/doctrine/base/BaseJobeetJob.class.php',
  'jobeetaffiliate' => 'E:/projets epitech/tuto-symfo-1-4/lib/model/doctrine/JobeetAffiliate.class.php',
  'jobeetaffiliatetable' => 'E:/projets epitech/tuto-symfo-1-4/lib/model/doctrine/JobeetAffiliateTable.class.php',
  'jobeetcategory' => 'E:/projets epitech/tuto-symfo-1-4/lib/model/doctrine/JobeetCategory.class.php',
  'jobeetcategoryaffiliate' => 'E:/projets epitech/tuto-symfo-1-4/lib/model/doctrine/JobeetCategoryAffiliate.class.php',
  'jobeetcategoryaffiliatetable' => 'E:/projets epitech/tuto-symfo-1-4/lib/model/doctrine/JobeetCategoryAffiliateTable.class.php',
  'jobeetcategorytable' => 'E:/projets epitech/tuto-symfo-1-4/lib/model/doctrine/JobeetCategoryTable.class.php',
  'jobeetjob' => 'E:/projets epitech/tuto-symfo-1-4/lib/model/doctrine/JobeetJob.class.php',
  'jobeetjobtable' => 'E:/projets epitech/tuto-symfo-1-4/lib/model/doctrine/JobeetJobTable.class.php',

  // application
  'myuser' => 'E:/projets epitech/tuto-symfo-1-4/apps/frontend/lib/myUser.class.php',

  // modules
);
